// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tublmdaefaazvphluinq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1YmxtZGFlZmFhenZwaGx1aW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODg4MDYsImV4cCI6MjA2ODI2NDgwNn0.N6q6aUfqcYCEeCJ5imdyPK4PqZ2pCpMleuTRUdtc8m0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});